import React, {
  createContext,
  useContext,
  useEffect,
  useState,
} from 'react';

import { useAuth } from '@/context/AuthenticationContext';
import {
  addDoc,
  updateDoc,
  collection,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  doc,
  deleteDoc,
} from 'firebase/firestore';


import { db } from '@/services/firebase';
import type { ApplicationStatus, JobApplication } from '@/types/JobApplication';

// New application without an ID (generated by Firestore).
type NewJobApplication = {
  company: string;
  position: string;
  status: ApplicationStatus;
  location?: string;
  notes?: string;
};

// Context for the rest of app
type ApplicationsContextValue = {
  applications: JobApplication[];
  isLoading: boolean;
  addApplication: (application: NewJobApplication) => Promise<void>;
  updateApplication: (id: string, updates: Partial<NewJobApplication>) => Promise<void>;
  deleteApplication: (id: string) => Promise<void>;
};

const ApplicationsContext = createContext<ApplicationsContextValue | undefined>(
  undefined
);

// App state
export function ApplicationsProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  // List of applications from Firestore.
  const [applications, setApplications] = useState<JobApplication[]>([]);

  const [isLoading, setIsLoading] = useState(true);

  const { user } = useAuth();

  useEffect(() => {
    if (!user) {
      setApplications([]);
      setIsLoading(false);
      return;
    }


    // Reference to Firestore collection
    const applicationsRef = collection(db, 'users', user.uid, 'applications');

    // Query for applications in descending order of update
    const applicationsQuery = query(
      applicationsRef,
      orderBy('updatedAt', 'desc')
    );

    // runs when Firestore data changes
    const unsubscribe = onSnapshot(applicationsQuery, (snapshot) => {
      // Map Firestore documents to JobApplication objects.
      const firestoreApplications: JobApplication[] = snapshot.docs.map(
        (doc) => {
          const data = doc.data();
          return {
            id: doc.id,
            company: data.company,
            position: data.position,
            status: data.status,
            location: data.location,
            notes: data.notes,
            createdAt: data.createdAt ? data.createdAt.toDate() : null,
            updatedAt: data.updatedAt ? data.updatedAt.toDate() : null,
          };
        }
      );

      // Update React state with the applications from Firestore
      setApplications(firestoreApplications);

      setIsLoading(false);
    });

    // Cleanup when component unmounts
    return unsubscribe;
  }, [user]);

  // Add new application to Firestore
  async function addApplication(application: NewJobApplication) {
    if (user) {
      await addDoc(collection(db, 'users', user.uid, 'applications'), {
        company: application.company,
        position: application.position,
        status: application.status,
        location: application.location ?? '',
        notes: application.notes ?? '',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });
    } else {
      throw new Error('User must be authenticated to add applications.');
    }
  }

  // Save an existing application in Firestore
  async function updateApplication(id: string, updates: Partial<NewJobApplication>) {
    if (!user) throw new Error('User must be authenticated.');
    await updateDoc(doc(db, 'users', user.uid, 'applications', id), {
      ...updates,
      updatedAt: serverTimestamp(),
    });
  }

  // Delete an application from Firestore
  async function deleteApplication(id: string) {
    if (!user) throw new Error('User must be authenticated.');
    await deleteDoc(doc(db, 'users', user.uid, 'applications', id));
  }

  // Value provided to the rest of the app
  const value: ApplicationsContextValue = {
    applications,
    isLoading,
    addApplication,
    updateApplication,
    deleteApplication
  };

  return (
    <ApplicationsContext.Provider value={value}>
      {children}
    </ApplicationsContext.Provider>
  );
}

// Hook to access the applications context in other components
export function useApplications() {
  const context = useContext(ApplicationsContext);

  // Error if used outside of ApplicationsProvider
  if (context === undefined) {
    throw new Error(
      'useApplications must be used inside an ApplicationsProvider'
    );
  }

  return context;
}